---
- name: Build and deploy Java Tomcat app on Minikube
  hosts: localhost
  gather_facts: no # No need for facts in this simple playbook

  vars:
    # --- Project/Image variables ---
    project_root_path: "{{ lookup('env', 'WORKSPACE') | default(ansible_facts.env.PWD, true) }}" # More robust way to get project root
    image_name: aman8997abc/my-tomcat-app # Your Docker Hub username/repo name
    image_tag: 1.0                       # Tag matching your manual build
    
    # --- Kubernetes application variables (make consistent with your .yaml files) ---
    k8s_app_name: aman-abc-tech          # Label/selector used in K8s YAMLs
    deployment_name: aman-abc-tech-deployment # Name of the K8s Deployment
    service_name: aman-abc-tech-service   # Name of the K8s Service
    k8s_container_port: 8080             # Port application listens on inside the container (Tomcat)
    k8s_service_port: 80                 # Port the K8s Service listens on externally (e.g., HTTP)
    k8s_service_type: NodePort           # How to expose the service (NodePort for Minikube)
    namespace: default                   # Kubernetes namespace

    # --- Docker Hub credentials (passed as extra-vars or Jenkins credentials) ---
    dockerhub_username: "{{ lookup('env', 'DOCKERHUB_USERNAME') | default(omit) }}"
    dockerhub_password: "{{ lookup('env', 'DOCKERHUB_PASSWORD') | default(omit) }}"

  tasks:
    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build
        build:
          path: "{{ project_root_path }}" # Build context is the project root where Dockerfile and target/ are
          args:
            WAR_FILE_NAME: "ABCtechnologies-1.0.war" # Pass the WAR file name as a build argument
      register: docker_build_result
      changed_when: docker_build_result.changed or (docker_build_result.image is defined and docker_build_result.image.id is defined)
      failed_when: docker_build_result.failed

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
        registry: docker.io
      when: dockerhub_username is defined and dockerhub_password is defined # Only run if credentials are provided
      no_log: true # Prevent sensitive info from being logged

    - name: Push Docker image to Docker Hub
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: local
        push: true
      when: dockerhub_username is defined and dockerhub_password is defined # Only push if credentials are provided

    - name: Delete existing Kubernetes deployment (if any)
      shell: "kubectl delete deployment {{ deployment_name }} --namespace {{ namespace }} --ignore-not-found"
      args:
        executable: /bin/bash
      # No environment: KUBECONFIG here

    - name: Delete existing Kubernetes service (if any)
      shell: "kubectl delete service {{ service_name }} --namespace {{ namespace }} --ignore-not-found"
      args:
        executable: /bin/bash
      # No environment: KUBECONFIG here

    - name: Apply new Kubernetes deployment and service
      # Assuming your k8s YAMLs are in a subfolder named 'k8s' directly under project_root_path
      shell: |
        kubectl apply -f {{ project_root_path }}/k8s/deployment.yaml
        kubectl apply -f {{ project_root_path }}/k8s/service.yaml
      args:
        executable: /bin/bash
      # No environment: KUBECONFIG here - THIS IS THE CRITICAL CHANGE!

    - name: Wait for deployment rollout to complete
      shell: "kubectl rollout status deployment/{{ deployment_name }} --timeout=300s --namespace {{ namespace }}"
      args:
        executable: /bin/bash

    - name: Get Minikube service URL
      shell: "minikube service {{ service_name }} --url --namespace {{ namespace }}"
      register: minikube_service_url
      # No environment: KUBECONFIG here

    - name: Display Minikube service URL
      debug:
        msg: "Application available at: {{ minikube_service_url.stdout }}"

    - name: Verify application accessibility
      uri:
        url: "{{ minikube_service_url.stdout }}"
        method: GET
        status_code: [200, 301, 302] # Allow redirects for web apps
        validate_certs: false # Use false for development/self-signed certs
      register: uri_result
      changed_when: false
      failed_when: uri_result.status not in [200, 301, 302]
      
    - debug:
        msg: "Application verification successful!"
      when: uri_result.status in [200, 301, 302]
